//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCasa.WSGestioneChiamate {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/WSChiamatePerse")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestCasa.WSGestioneChiamate.ResponseInsert))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] InfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] WarningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Infos {
            get {
                return this.InfosField;
            }
            set {
                if ((object.ReferenceEquals(this.InfosField, value) != true)) {
                    this.InfosField = value;
                    this.RaisePropertyChanged("Infos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Warnings {
            get {
                return this.WarningsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningsField, value) != true)) {
                    this.WarningsField = value;
                    this.RaisePropertyChanged("Warnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseInsert", Namespace="http://schemas.datacontract.org/2004/07/WSChiamatePerse")]
    [System.SerializableAttribute()]
    public partial class ResponseInsert : TestCasa.WSGestioneChiamate.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AffectedRowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AffectedRows {
            get {
                return this.AffectedRowsField;
            }
            set {
                if ((this.AffectedRowsField.Equals(value) != true)) {
                    this.AffectedRowsField = value;
                    this.RaisePropertyChanged("AffectedRows");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSGestioneChiamate.IGestioneChiamate")]
    public interface IGestioneChiamate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InsertJson", ReplyAction="http://tempuri.org/IGestioneChiamate/InsertJsonResponse")]
        TestCasa.WSGestioneChiamate.ResponseInsert InsertJson(string jsonArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InsertJson", ReplyAction="http://tempuri.org/IGestioneChiamate/InsertJsonResponse")]
        System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InsertJsonAsync(string jsonArray);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestioneChiamateChannel : TestCasa.WSGestioneChiamate.IGestioneChiamate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestioneChiamateClient : System.ServiceModel.ClientBase<TestCasa.WSGestioneChiamate.IGestioneChiamate>, TestCasa.WSGestioneChiamate.IGestioneChiamate {
        
        public GestioneChiamateClient() {
        }
        
        public GestioneChiamateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestioneChiamateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneChiamateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneChiamateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestCasa.WSGestioneChiamate.ResponseInsert InsertJson(string jsonArray) {
            return base.Channel.InsertJson(jsonArray);
        }
        
        public System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InsertJsonAsync(string jsonArray) {
            return base.Channel.InsertJsonAsync(jsonArray);
        }
    }
}
