//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCasa.WSGestioneChiamate {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/WSChiamatePerse")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestCasa.WSGestioneChiamate.ResponseInsert))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] InfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] WarningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Infos {
            get {
                return this.InfosField;
            }
            set {
                if ((object.ReferenceEquals(this.InfosField, value) != true)) {
                    this.InfosField = value;
                    this.RaisePropertyChanged("Infos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Warnings {
            get {
                return this.WarningsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningsField, value) != true)) {
                    this.WarningsField = value;
                    this.RaisePropertyChanged("Warnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseInsert", Namespace="http://schemas.datacontract.org/2004/07/WSChiamatePerse")]
    [System.SerializableAttribute()]
    public partial class ResponseInsert : TestCasa.WSGestioneChiamate.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AffectedRowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AffectedRows {
            get {
                return this.AffectedRowsField;
            }
            set {
                if ((this.AffectedRowsField.Equals(value) != true)) {
                    this.AffectedRowsField = value;
                    this.RaisePropertyChanged("AffectedRows");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChiamataSOi", Namespace="http://schemas.datacontract.org/2004/07/WSChiamatePerse")]
    [System.SerializableAttribute()]
    public partial class ChiamataSOi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataOraFineChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataOraInizioChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ExtIDChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ExtIDOperatoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IDExtSollecitoChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroChiamataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrioritaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CognomeChiamata {
            get {
                return this.CognomeChiamataField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeChiamataField, value) != true)) {
                    this.CognomeChiamataField = value;
                    this.RaisePropertyChanged("CognomeChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataOraFineChiamata {
            get {
                return this.DataOraFineChiamataField;
            }
            set {
                if ((this.DataOraFineChiamataField.Equals(value) != true)) {
                    this.DataOraFineChiamataField = value;
                    this.RaisePropertyChanged("DataOraFineChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataOraInizioChiamata {
            get {
                return this.DataOraInizioChiamataField;
            }
            set {
                if ((this.DataOraInizioChiamataField.Equals(value) != true)) {
                    this.DataOraInizioChiamataField = value;
                    this.RaisePropertyChanged("DataOraInizioChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ExtIDChiamata {
            get {
                return this.ExtIDChiamataField;
            }
            set {
                if ((this.ExtIDChiamataField.Equals(value) != true)) {
                    this.ExtIDChiamataField = value;
                    this.RaisePropertyChanged("ExtIDChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ExtIDOperatore {
            get {
                return this.ExtIDOperatoreField;
            }
            set {
                if ((this.ExtIDOperatoreField.Equals(value) != true)) {
                    this.ExtIDOperatoreField = value;
                    this.RaisePropertyChanged("ExtIDOperatore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IDExtSollecitoChiamata {
            get {
                return this.IDExtSollecitoChiamataField;
            }
            set {
                if ((this.IDExtSollecitoChiamataField.Equals(value) != true)) {
                    this.IDExtSollecitoChiamataField = value;
                    this.RaisePropertyChanged("IDExtSollecitoChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoChiamata {
            get {
                return this.InfoChiamataField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoChiamataField, value) != true)) {
                    this.InfoChiamataField = value;
                    this.RaisePropertyChanged("InfoChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoChiamata {
            get {
                return this.MotivoChiamataField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoChiamataField, value) != true)) {
                    this.MotivoChiamataField = value;
                    this.RaisePropertyChanged("MotivoChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeChiamata {
            get {
                return this.NomeChiamataField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeChiamataField, value) != true)) {
                    this.NomeChiamataField = value;
                    this.RaisePropertyChanged("NomeChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroChiamata {
            get {
                return this.NumeroChiamataField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroChiamataField, value) != true)) {
                    this.NumeroChiamataField = value;
                    this.RaisePropertyChanged("NumeroChiamata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Priorita {
            get {
                return this.PrioritaField;
            }
            set {
                if ((this.PrioritaField.Equals(value) != true)) {
                    this.PrioritaField = value;
                    this.RaisePropertyChanged("Priorita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSGestioneChiamate.IGestioneChiamate")]
    public interface IGestioneChiamate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateJO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateJOResponse")]
        TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateJO(string jsonArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateJO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateJOResponse")]
        System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateJOAsync(string jsonArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateJJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateJJResponse")]
        string InserisciChiamateJJ(string jsonArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateJJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateJJResponse")]
        System.Threading.Tasks.Task<string> InserisciChiamateJJAsync(string jsonArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateJI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateJIResponse")]
        int InserisciChiamateJI(string jsonArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateJI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateJIResponse")]
        System.Threading.Tasks.Task<int> InserisciChiamateJIAsync(string jsonArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOOResponse")]
        TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateLOO(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOOResponse")]
        System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateLOOAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOJResponse")]
        string InserisciChiamateLOJ(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOJResponse")]
        System.Threading.Tasks.Task<string> InserisciChiamateLOJAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOIResponse")]
        int InserisciChiamateLOI(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateLOIResponse")]
        System.Threading.Tasks.Task<int> InserisciChiamateLOIAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOOResponse")]
        TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateAOO(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOOResponse")]
        System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateAOOAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOJResponse")]
        string InserisciChiamateAOJ(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOJResponse")]
        System.Threading.Tasks.Task<string> InserisciChiamateAOJAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOIResponse")]
        int InserisciChiamateAOI(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateAOIResponse")]
        System.Threading.Tasks.Task<int> InserisciChiamateAOIAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateOO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateOOResponse")]
        TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateOO(TestCasa.WSGestioneChiamate.ChiamataSOi data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateOO", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateOOResponse")]
        System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateOOAsync(TestCasa.WSGestioneChiamate.ChiamataSOi data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateOJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateOJResponse")]
        string InserisciChiamateOJ(TestCasa.WSGestioneChiamate.ChiamataSOi data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateOJ", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateOJResponse")]
        System.Threading.Tasks.Task<string> InserisciChiamateOJAsync(TestCasa.WSGestioneChiamate.ChiamataSOi data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateOI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateOIResponse")]
        int InserisciChiamateOI(TestCasa.WSGestioneChiamate.ChiamataSOi data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestioneChiamate/InserisciChiamateOI", ReplyAction="http://tempuri.org/IGestioneChiamate/InserisciChiamateOIResponse")]
        System.Threading.Tasks.Task<int> InserisciChiamateOIAsync(TestCasa.WSGestioneChiamate.ChiamataSOi data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestioneChiamateChannel : TestCasa.WSGestioneChiamate.IGestioneChiamate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestioneChiamateClient : System.ServiceModel.ClientBase<TestCasa.WSGestioneChiamate.IGestioneChiamate>, TestCasa.WSGestioneChiamate.IGestioneChiamate {
        
        public GestioneChiamateClient() {
        }
        
        public GestioneChiamateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestioneChiamateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneChiamateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneChiamateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateJO(string jsonArray) {
            return base.Channel.InserisciChiamateJO(jsonArray);
        }
        
        public System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateJOAsync(string jsonArray) {
            return base.Channel.InserisciChiamateJOAsync(jsonArray);
        }
        
        public string InserisciChiamateJJ(string jsonArray) {
            return base.Channel.InserisciChiamateJJ(jsonArray);
        }
        
        public System.Threading.Tasks.Task<string> InserisciChiamateJJAsync(string jsonArray) {
            return base.Channel.InserisciChiamateJJAsync(jsonArray);
        }
        
        public int InserisciChiamateJI(string jsonArray) {
            return base.Channel.InserisciChiamateJI(jsonArray);
        }
        
        public System.Threading.Tasks.Task<int> InserisciChiamateJIAsync(string jsonArray) {
            return base.Channel.InserisciChiamateJIAsync(jsonArray);
        }
        
        public TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateLOO(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateLOO(data);
        }
        
        public System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateLOOAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateLOOAsync(data);
        }
        
        public string InserisciChiamateLOJ(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateLOJ(data);
        }
        
        public System.Threading.Tasks.Task<string> InserisciChiamateLOJAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateLOJAsync(data);
        }
        
        public int InserisciChiamateLOI(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateLOI(data);
        }
        
        public System.Threading.Tasks.Task<int> InserisciChiamateLOIAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateLOIAsync(data);
        }
        
        public TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateAOO(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateAOO(data);
        }
        
        public System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateAOOAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateAOOAsync(data);
        }
        
        public string InserisciChiamateAOJ(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateAOJ(data);
        }
        
        public System.Threading.Tasks.Task<string> InserisciChiamateAOJAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateAOJAsync(data);
        }
        
        public int InserisciChiamateAOI(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateAOI(data);
        }
        
        public System.Threading.Tasks.Task<int> InserisciChiamateAOIAsync(TestCasa.WSGestioneChiamate.ChiamataSOi[] data) {
            return base.Channel.InserisciChiamateAOIAsync(data);
        }
        
        public TestCasa.WSGestioneChiamate.ResponseInsert InserisciChiamateOO(TestCasa.WSGestioneChiamate.ChiamataSOi data) {
            return base.Channel.InserisciChiamateOO(data);
        }
        
        public System.Threading.Tasks.Task<TestCasa.WSGestioneChiamate.ResponseInsert> InserisciChiamateOOAsync(TestCasa.WSGestioneChiamate.ChiamataSOi data) {
            return base.Channel.InserisciChiamateOOAsync(data);
        }
        
        public string InserisciChiamateOJ(TestCasa.WSGestioneChiamate.ChiamataSOi data) {
            return base.Channel.InserisciChiamateOJ(data);
        }
        
        public System.Threading.Tasks.Task<string> InserisciChiamateOJAsync(TestCasa.WSGestioneChiamate.ChiamataSOi data) {
            return base.Channel.InserisciChiamateOJAsync(data);
        }
        
        public int InserisciChiamateOI(TestCasa.WSGestioneChiamate.ChiamataSOi data) {
            return base.Channel.InserisciChiamateOI(data);
        }
        
        public System.Threading.Tasks.Task<int> InserisciChiamateOIAsync(TestCasa.WSGestioneChiamate.ChiamataSOi data) {
            return base.Channel.InserisciChiamateOIAsync(data);
        }
    }
}
